modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

displayTest="MATCH_VERSION"

[[mods]]
modId="generatormod"
version="${file.jarVersion}"
displayName="Generator Mod"
credits="Created for automated item generation"
authors="ChatGPT"
description='''
A simple generator management interface that lets you queue vanilla resources while the world is offline.
'''

[[dependencies.generatormod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.generatormod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
